spring:

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

  profiles:
    include:
      - security
      - db

logging:
  level:
    root: info
  file:
    path: ${user.home}/logs/

img:
  dir: ${user.home}/img/

video:
  dir: ${user.home}/video/


cloud:
  s3:
    bucket: vingterview
    dir_image : image/
    dir_video : video/

  region : ap-northeast-2
  stack :
    auto : false