spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
  datasource:
    url: jdbc:h2:tcp://localhost/~/ving
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

  profiles:
    include: security

logging:
  level:
    root: info
  file:
    path: ${user.home}/logs/

img:
  dir: ${user.home}/img/

video:
  dir: ${user.home}/video/


cloud:
  s3:
    bucket: vingterview
    dir_image : image/
    dir_video : video/

  region : ap-northeast-2
  stack :
    auto : false