spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ving
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 500


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace



img:
  dir: C:\Users\lms06\Documents\project\vingterview\src\main\resources\img\

video:
  dir: C:\Users\lms06\Documents\project\vingterview\src\main\resources\video\