package ving.vingterview.websocket;

public enum MessageType {
    CREATE, START, QUESTION, PARTICIPATE, FINISH_PARTICIPATE, START_VIDEO ,FINISH_VIDEO, INFO, TURN, VIDEO, POLL, FINISH_POLL, RESULT, NEXT, FINISH_GAME,


}
